version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.17.14
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
     - 5601:5601
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  api:
    container_name: api
    image: "api:latest"
    networks:
      - default
    ports:
      - "5000:5000"
    depends_on:
      - "db"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PermissionsConnectionString=Persist Security Info=False;User ID=sa;Password=SqlPass123!;Initial Catalog=CQRS;Server=db;TrustServerCertificate=True;
  db:
    container_name: db-sqlserver
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    hostname: sql1
    environment:
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SqlPass123!
volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
  sqlserver-data:
    driver: local